apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanami-ai
  labels:
    app: hanami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanami
  template:
    metadata:
      labels:
        app: hanami
    spec:
      initContainers:
      - name: dashboard-container
        image: registry.kitsunemimi.moe:5000/hanami_ai_dashboard:0.1.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        command: ["cp", "-r", "/etc/HanamiAI-Dashboard", "/etc/torii/"]
        volumeMounts:
        - name: dashboard-volume
          mountPath: /etc/torii/HanamiAI-Dashboard
      containers:
      - name: misaki
        image: registry.kitsunemimi.moe:5000/misaki_guard:0.1.0
        imagePullPolicy: Always
        env:
        - name: HANAMI_ADMIN_USER_ID
          value: {{ .Values.user_id }}
        - name: HANAMI_ADMIN_USER_NAME
          value: {{ .Values.user_name }}
        - name: HANAMI_ADMIN_PASSWORD
          value: {{ .Values.user_pw }}
        volumeMounts:
        - name: misaki-config
          mountPath: /etc/misaki/misaki.conf
          subPath: misaki.conf
        - name: endpoints-config
          mountPath: /etc/misaki/endpoints
          subPath: endpoints
        - name: policies-config
          mountPath: /etc/misaki/policies
          subPath: policies
        - name: token-key
          mountPath: /etc/misaki/token_key
          subPath: token_key
        - name: sakura-files-volume
          mountPath: /etc/misaki/sakura-files
        - name: hanami-sockets-volume
          mountPath: /tmp/hanami
      - name: shiori
        image: registry.kitsunemimi.moe:5000/shiori_archive:0.1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: shiori-config
          mountPath: /etc/shiori/shiori.conf
          subPath: shiori.conf
        - name: endpoints-config
          mountPath: /etc/shiori/endpoints
          subPath: endpoints
        - name: sakura-files-volume
          mountPath: /etc/shiori/sakura-files
        - name: errors-volume
          mountPath: /etc/shiori/errors
        - name: audit-volume
          mountPath: /etc/shiori/audit
        - name: cluster-snapshots-volume
          mountPath: /etc/shiori/cluster_snapshots
        - name: train-data-volume
          mountPath: /etc/shiori/train_data
        - name: results-volume
          mountPath: /etc/shiori/results
        - name: hanami-sockets-volume
          mountPath: /tmp/hanami
      - name: kyouko
        image: registry.kitsunemimi.moe:5000/kyouko_mind:0.1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: kyouko-config
          mountPath: /etc/kyouko/kyouko.conf
          subPath: kyouko.conf
        - name: endpoints-config
          mountPath: /etc/kyouko/endpoints
          subPath: endpoints
        - name: sakura-files-volume
          mountPath: /etc/kyouko/sakura-files
        - name: hanami-sockets-volume
          mountPath: /tmp/hanami
      - name: azuki
        image: registry.kitsunemimi.moe:5000/azuki_heart:0.1.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: azuki-config
          mountPath: /etc/azuki/azuki.conf
          subPath: azuki.conf
        - name: endpoints-config
          mountPath: /etc/azuki/endpoints
          subPath: endpoints
        - name: sakura-files-volume
          mountPath: /etc/azuki/sakura-files
        - name: hanami-sockets-volume
          mountPath: /tmp/hanami
      - name: torii
        image: registry.kitsunemimi.moe:5000/torii_gateway:0.1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: torii-config
          mountPath: /etc/torii/torii.conf
          subPath: torii.conf
        - name: endpoints-config
          mountPath: /etc/torii/endpoints
          subPath: endpoints
        - name: sakura-files-volume
          mountPath: /etc/torii/sakura-files
        - name: hanami-sockets-volume
          mountPath: /tmp/hanami
        - name: dashboard-volume
          mountPath: /etc/torii/HanamiAI-Dashboard
        ports:
        - containerPort: 1337
          name: torii-port
      volumes:
        - name: misaki-config
          configMap:
            name: misaki-config
        - name: shiori-config
          configMap:
            name: shiori-config
        - name: kyouko-config
          configMap:
            name: kyouko-config
        - name: azuki-config
          configMap:
            name: azuki-config
        - name: torii-config
          configMap:
            name: torii-config
        - name: endpoints-config
          configMap:
            name: endpoints-config
        - name: policies-config
          configMap:
            name: policies-config
        - name: token-key
          configMap:
            name: token-key
        - name: sakura-files-volume
          emptyDir: {}
        - name: errors-volume
          emptyDir: {}
        - name: audit-volume
          emptyDir: {}
        - name: cluster-snapshots-volume
          emptyDir: {}
        - name: train-data-volume
          emptyDir: {}
        - name: results-volume
          emptyDir: {}
        - name: hanami-sockets-volume
          emptyDir: {}
        - name: dashboard-volume
          emptyDir: {}
