apiVersion: v1
metadata:
  name: kyouko-config
data:
  kyouko.conf: |+
    [DEFAULT]
    #debug = true
    log_path = "/var/log/kyouko"
    address = "/tmp/hanami/kyouko.uds"
    database = "/etc/kyouko/kyouko_db"

    [misaki]
    address = "/tmp/hanami/misaki.uds"

    [shiori]
    address = "/tmp/hanami/shiori.uds"

kind: ConfigMap
