apiVersion: v1
metadata:
  name: shiori-config
data:
  shiori.conf: |+
    [DEFAULT]
    #debug = True
    log_path = "/var/log/shiori"
    address = "/tmp/hanami/shiori.uds"
    database = "/etc/shiori/shiori_db"

    [shiori]
    data_set_location = "/etc/shiori/files"
    cluster_snapshot_location = "/etc/shiori/files"

    [misaki]
    address = "/tmp/hanami/misaki.uds"

kind: ConfigMap
