apiVersion: v1
metadata:
  name: shiori-config
data:
  shiori.conf: |+
    [DEFAULT]
    #debug = True
    log_path = "/var/log/shiori"
    sakura-file-locaion = "/etc/shiori/sakura-files"
    address = "/tmp/hanami/shiori.uds"
    endpoints = "/etc/shiori/endpoints"
    database = "/etc/shiori/shiori_db"

    [shiori]
    data_set_location = "/etc/shiori/train_data"
    result_location = "/etc/shiori/results"
    error_location = "/etc/shiori/errors"
    audit_location = "/etc/shiori/audit"
    cluster_snapshot_location = "/etc/shiori/cluster_snapshots"

    [misaki]
    address = "/tmp/hanami/misaki.uds"

kind: ConfigMap
