apiVersion: v1
data:
  azuki.conf: |
    [DEFAULT]
    #debug = True
    log_path = "/var/log/azuki"
    sakura-file-locaion = "/etc/azuki/sakura-files"
    address = "/tmp/hanami/azuki.uds"
    endpoints = "/etc/azuki/endpoints"
    database = "/etc/azuki/azuki_db"

    [torii]
    address = "/tmp/hanami/torii.uds"

    [misaka]
    address = "/tmp/hanami/misaka.uds"

    [sagiri]
    address = "/tmp/hanami/sagiri.uds"

    [kyouko]
    address = "/tmp/hanami/kyouko.uds"
kind: ConfigMap
