apiVersion: v1
data:
  kyouko.conf: |+
    [DEFAULT]
    #debug = true
    log_path = "/var/log/kyouko"
    sakura-file-locaion = "/etc/kyouko/sakura-files"
    address = "/tmp/hanami/kyouko.uds"
    endpoints = "/etc/kyouko/endpoints"
    database = "/etc/kyouko/kyouko_db"

    [misaka]
    address = "/tmp/hanami/misaka.uds"

    [sagiri]
    address = "/tmp/hanami/sagiri.uds"

kind: ConfigMap
