apiVersion: v1
data:
  torii.conf: |
    [DEFAULT]
    #debug = True
    log_path = "/var/log/torii"
    address = "/tmp/hanami/torii.uds"
    endpoints = "/etc/torii/endpoints"

    [sakura]
    enable = True
    ip = "0.0.0.0"
    certificate = "/etc/torii/cert.pem"
    key = "/etc/torii/key.pem"
    port = 1338

    [http]
    enable = True
    ip = "0.0.0.0"
    certificate = "/etc/torii/cert.pem"
    key = "/etc/torii/key.pem"
    dashboard_files = "/home/neptune/Schreibtisch/Projekte/HanamiDashboard/src"
    port = 1337
    enable_dashboard = True

    [misaka]
    address = "/tmp/hanami/misaka.uds"

    #[azuki]
    #address = "/tmp/azuki.uds"

    [sagiri]
    address = "/tmp/hanami/sagiri.uds"

    [kyouko]
    address = "/tmp/hanami/kyouko.uds"
kind: ConfigMap
